export const LIVESTATS = {
  gameId: 5713255098,
  mapId: 11,
  gameMode: "CLASSIC",
  gameType: "MATCHED_GAME",
  gameQueueConfigId: 420,
  participants: [
    {
      teamId: 100,
      spell1Id: 4,
      spell2Id: 14,
      championId: 223,
      profileIconId: 551,
      summonerName: "Frogning",
      bot: false,
      summonerId: "_pItLybjT8V4XnjcEjgD8ahz7gTEQQnaPhodc5XfyTsAW4_Y",
      gameCustomizationObjects: [],
      perks: {
        perkIds: [8465, 8463, 8444, 8242, 8345, 8410, 5005, 5002, 5002],
        perkStyle: 8400,
        perkSubStyle: 8300,
      },
    },
    {
      teamId: 100,
      spell1Id: 7,
      spell2Id: 4,
      championId: 235,
      profileIconId: 4828,
      summonerName: "Simzet",
      bot: false,
      summonerId: "Jch6-lgT6dU_qsm-3AgG61HwyZjEYzE6rFQBli-zlJMB4kw",
      gameCustomizationObjects: [],
      perks: {
        perkIds: [9923, 8126, 8138, 8135, 8226, 8210, 5005, 5008, 5002],
        perkStyle: 8100,
        perkSubStyle: 8200,
      },
    },
    {
      teamId: 100,
      spell1Id: 11,
      spell2Id: 4,
      championId: 59,
      profileIconId: 4887,
      summonerName: "Wesleý",
      bot: false,
      summonerId: "LX9mkE_WIebje-VX0HS13MNgWkOw42OU2mRmu0vh9mst1WQ",
      gameCustomizationObjects: [],
      perks: {
        perkIds: [8112, 8143, 8136, 8106, 8014, 9104, 5005, 5008, 5002],
        perkStyle: 8100,
        perkSubStyle: 8000,
      },
    },
    {
      teamId: 100,
      spell1Id: 4,
      spell2Id: 14,
      championId: 92,
      profileIconId: 4077,
      summonerName: "lMileniuMl",
      bot: false,
      summonerId: "7Zhq6RhGmztDM5t7It7m5CMzUhkzwfOyqdtvW5BsUx77ud_i",
      gameCustomizationObjects: [],
      perks: {
        perkIds: [8010, 9111, 9104, 8299, 8210, 8275, 5008, 5008, 5002],
        perkStyle: 8000,
        perkSubStyle: 8200,
      },
    },
    {
      teamId: 100,
      spell1Id: 4,
      spell2Id: 14,
      championId: 38,
      profileIconId: 4057,
      summonerName: "xDrZ",
      bot: false,
      summonerId: "byv4nGZIfLVpnLhi9DhIyaktLXz41vTgzJDnW9nP-_0HwV0",
      gameCustomizationObjects: [],
      perks: {
        perkIds: [8021, 8009, 9105, 8014, 8139, 8106, 5008, 5008, 5003],
        perkStyle: 8000,
        perkSubStyle: 8100,
      },
    },
    {
      teamId: 200,
      spell1Id: 14,
      spell2Id: 4,
      championId: 157,
      profileIconId: 3614,
      summonerName: "Pichula 3nojada",
      bot: false,
      summonerId: "z0XGncVfxO03ZzFht195_lMb3UXA5nveG6-CZ69QskxigHo",
      gameCustomizationObjects: [],
      perks: {
        perkIds: [8008, 9111, 9104, 8299, 8473, 8242, 5005, 5008, 5002],
        perkStyle: 8000,
        perkSubStyle: 8400,
      },
    },
    {
      teamId: 200,
      spell1Id: 4,
      spell2Id: 7,
      championId: 81,
      profileIconId: 4074,
      summonerName: "WW Gabibo",
      bot: false,
      summonerId: "qORBGp3xmv6TvGoc2CIUM3ajnF8ZmiTuS1TIlenFlDN7PPU",
      gameCustomizationObjects: [],
      perks: {
        perkIds: [8369, 8304, 8345, 8347, 9111, 8014, 5005, 5008, 5002],
        perkStyle: 8300,
        perkSubStyle: 8000,
      },
    },
    {
      teamId: 200,
      spell1Id: 14,
      spell2Id: 4,
      championId: 5,
      profileIconId: 4884,
      summonerName: "shelovesdanii",
      bot: false,
      summonerId: "dLkeUhSc0PJjkd4oy3_9cTjb_KyEck7_7T-6UQcKZKFACcZD",
      gameCustomizationObjects: [],
      perks: {
        perkIds: [8008, 9111, 9104, 8299, 8304, 8321, 5008, 5008, 5002],
        perkStyle: 8000,
        perkSubStyle: 8300,
      },
    },
    {
      teamId: 200,
      spell1Id: 3,
      spell2Id: 4,
      championId: 147,
      profileIconId: 745,
      summonerName: "Red Carrot",
      bot: false,
      summonerId: "7cVeUcznOKEW8VvYRqt3RSAgFI0NZJyonLEDYIWlq7iouHfA",
      gameCustomizationObjects: [],
      perks: {
        perkIds: [8229, 8226, 8233, 8237, 8473, 8453, 5008, 5008, 5003],
        perkStyle: 8200,
        perkSubStyle: 8400,
      },
    },
    {
      teamId: 200,
      spell1Id: 4,
      spell2Id: 11,
      championId: 131,
      profileIconId: 29,
      summonerName: "Last in team",
      bot: false,
      summonerId: "6uUGKmUIQbsteYIkuztUM0FM4pN9kvSUQA7xGmKcMqkPzVNY",
      gameCustomizationObjects: [],
      perks: {
        perkIds: [8010, 9111, 9104, 8299, 8429, 8451, 5005, 5008, 5002],
        perkStyle: 8000,
        perkSubStyle: 8400,
      },
    },
  ],
  observers: { encryptionKey: "XnNO86DZpBNUIH/98YEQdgy9m3i/HBWn" },
  platformId: "EUW1",
  bannedChampions: [
    { championId: 234, teamId: 100, pickTurn: 1 },
    { championId: 35, teamId: 100, pickTurn: 2 },
    { championId: 117, teamId: 100, pickTurn: 3 },
    { championId: 40, teamId: 100, pickTurn: 4 },
    { championId: 23, teamId: 100, pickTurn: 5 },
    { championId: 53, teamId: 200, pickTurn: 6 },
    { championId: 221, teamId: 200, pickTurn: 7 },
    { championId: 711, teamId: 200, pickTurn: 8 },
    { championId: 166, teamId: 200, pickTurn: 9 },
    { championId: -1, teamId: 200, pickTurn: 10 },
  ],
  gameStartTime: 1644061468319,
  gameLength: 99,
};

export const POSTGAME = {
  metadata: {
    dataVersion: "2",
    matchId: "EUW1_5713136284",
    participants: [
      "ftytpWNyvgH6gXIzyd25SMUb6-FQQseSWDXan_q5zjMYeJtiErAHngH88YRrvFKgZQw0iVXYnHvnNw",
      "K1lgq4Ykend81kgwKN0EBlSWDnNAzGWCka52n9k4cYHe4rpYjWVK-cLD1Q3sxr-zug5g1yVrjGXmaA",
      "LP0h7tup-4EjCm0tvOUb1q2UaCpyxuexEzovYriTwQv61eYelTFatKW9yVrwuC4P-Gawqy2KoZN0Tw",
      "vplw3YSacqeCjFv_ylDMVfefdmbmfbCuZbGHjR4kZizwFZ2EDwmqihvLg1Ws9MiF57cyQgqoFVnGcQ",
      "z0GHTgpcCucbXZoOdi0xjdiObG5ntKi5X4E9QKUFjMbZusb2X6FJrgE_J6utv1qwUGnNGaKkRT4rwg",
      "ZyAlloitlXWMMqarC45cVU04Wy20jt8ivQAbUXipYeH4QJaG8bbKEe2ce3KScwroiyoscLT1s0OMmw",
      "LHCBtlfzXPjV9LDyRsC8fQaJppitSwx5RFls-xzTHwKDgYauUutQwL5m5y3fwD2RERBcMBgiGPTaFQ",
      "0l86qSi2UIk4xuEjGoj7ifBUZqqtlGj07ZRQtEwqi9YM0NUtoEHJe0taiKrkgebdG7JLr9ZO9Q78Pg",
      "JHlfELT_G1bVM0J7_dH74PbOHF9ym-49nf5aT9eDL0k2jyrKI22PZ4foPCCh-RkxIMAh36q5Apk1-A",
      "0cnhrppdsw0JBuYQfvj8x-UoLCj-TwpEn4qS_GcJbY4yTQIGkSdYeZKalxJKWiGMmKTK3DENZHNg1g",
    ],
  },
  info: {
    gameCreation: 1644056932000,
    gameDuration: 879,
    gameEndTimestamp: 1644057893474,
    gameId: 5713136284,
    gameMode: "ARAM",
    gameName: "teambuilder-match-5713136284",
    gameStartTimestamp: 1644057014410,
    gameType: "MATCHED_GAME",
    gameVersion: "12.3.421.5967",
    mapId: 12,
    participants: [
      {
        assists: 36,
        baronKills: 0,
        bountyLevel: 0,
        challenges: {
          "12AssistStreakCount": 2,
          abilityUses: 159,
          acesBefore15Minutes: 4,
          alliedJungleMonsterKills: 0,
          baronTakedowns: 0,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 0,
          buffsStolen: 0,
          controlWardsPlaced: 0,
          damagePerMinute: 963.3319552678029,
          damageTakenOnTeamPercentage: 0.13916821322678036,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 5,
          doubleAces: 0,
          dragonTakedowns: 0,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 3534.776123046875,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 14,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          flawlessAces: 3,
          fullTeamTakedown: 6,
          gameLength: 879.2444117,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 660.4266322927486,
          hadAfkTeammate: 0,
          hadOpenNexus: 0,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerKillsEarlyJungle: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kda: 7.6,
          killParticipation: 1.0857142857142856,
          killsNearEnemyTurret: 0,
          killsOnLanersEarlyJungleAsJungler: 0,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 1,
          killsWithHelpFromEpicMonster: 0,
          laneMinionsFirst10Minutes: 6,
          laningPhaseGoldExpAdvantage: -0.05497097969055176,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 2,
          maxKillDeficit: 6,
          maxLevelLeadLaneOpponent: 2,
          moreEnemyJungleThanOpponent: -24,
          mostWardsDestroyedOneSweeper: 0,
          multiKillOneSpell: 0,
          multikills: 0,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 4005,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 0,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          poroExplosions: 0,
          riftHeraldTakedowns: 0,
          scuttleCrabKills: 0,
          shortestTimeToAceFromFirstTakedown: 17.417949600000043,
          skillshotsDodged: 140,
          skillshotsHit: 53,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 0,
          stealthWardsPlaced: 0,
          survivedSingleDigitHpCount: 0,
          takedownOnFirstTurret: 1,
          takedowns: 38,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirst25Minutes: 38,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 0,
          teamDamagePercentage: 0.08769137999955016,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 0,
          teleportTakedowns: 2,
          turretPlatesTaken: 0,
          turretTakedowns: 4,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 0,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 0,
          visionScorePerMinute: 0,
          wardTakedowns: 0,
          wardTakedownsBefore20M: 0,
          wardsGuarded: 0,
        },
        champExperience: 14394,
        champLevel: 15,
        championId: 267,
        championName: "Nami",
        championTransform: 0,
        consumablesPurchased: 1,
        damageDealtToBuildings: 1995,
        damageDealtToObjectives: 1995,
        damageDealtToTurrets: 1995,
        damageSelfMitigated: 4630,
        deaths: 5,
        detectorWardsPlaced: 0,
        doubleKills: 0,
        dragonKills: 0,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        goldEarned: 9677,
        goldSpent: 7435,
        individualPosition: "Invalid",
        inhibitorKills: 0,
        inhibitorTakedowns: 1,
        inhibitorsLost: 0,
        item0: 4005,
        item1: 3070,
        item2: 6616,
        item3: 3158,
        item4: 3114,
        item5: 1052,
        item6: 2052,
        itemsPurchased: 9,
        killingSprees: 0,
        kills: 2,
        lane: "NONE",
        largestCriticalStrike: 0,
        largestKillingSpree: 0,
        largestMultiKill: 1,
        longestTimeSpentLiving: 230,
        magicDamageDealt: 10157,
        magicDamageDealtToChampions: 5851,
        magicDamageTaken: 7769,
        neutralMinionsKilled: 0,
        nexusKills: 0,
        nexusLost: 0,
        nexusTakedowns: 1,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        participantId: 1,
        pentaKills: 0,
        perks: {
          statPerks: { defense: 5002, flex: 5008, offense: 5005 },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                { perk: 8112, var1: 680, var2: 0, var3: 0 },
                { perk: 8139, var1: 794, var2: 0, var3: 0 },
                { perk: 8138, var1: 30, var2: 0, var3: 0 },
                { perk: 8135, var1: 561, var2: 5, var3: 0 },
              ],
              style: 8100,
            },
            {
              description: "subStyle",
              selections: [
                { perk: 8237, var1: 270, var2: 0, var3: 0 },
                { perk: 8210, var1: 24, var2: 0, var3: 0 },
              ],
              style: 8200,
            },
          ],
        },
        physicalDamageDealt: 3959,
        physicalDamageDealtToChampions: 985,
        physicalDamageTaken: 5735,
        profileIcon: 3207,
        puuid:
          "ftytpWNyvgH6gXIzyd25SMUb6-FQQseSWDXan_q5zjMYeJtiErAHngH88YRrvFKgZQw0iVXYnHvnNw",
        quadraKills: 0,
        riotIdName: "",
        riotIdTagline: "",
        role: "SUPPORT",
        sightWardsBoughtInGame: 0,
        spell1Casts: 27,
        spell2Casts: 67,
        spell3Casts: 58,
        spell4Casts: 7,
        summoner1Casts: 5,
        summoner1Id: 7,
        summoner2Casts: 3,
        summoner2Id: 4,
        summonerId: "k-FVBT-B3M8jvRVGoZb-IWmuAqkHzXBt64C7SOkUadkYkV8",
        summonerLevel: 213,
        summonerName: "Hayku",
        teamEarlySurrendered: false,
        teamId: 100,
        teamPosition: "",
        timeCCingOthers: 21,
        timePlayed: 879,
        totalDamageDealt: 14116,
        totalDamageDealtToChampions: 6836,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 13831,
        totalHeal: 8989,
        totalHealsOnTeammates: 3534,
        totalMinionsKilled: 7,
        totalTimeCCDealt: 166,
        totalTimeSpentDead: 95,
        totalUnitsHealed: 5,
        tripleKills: 0,
        trueDamageDealt: 0,
        trueDamageDealtToChampions: 0,
        trueDamageTaken: 326,
        turretKills: 0,
        turretTakedowns: 4,
        turretsLost: 1,
        unrealKills: 0,
        visionScore: 0,
        visionWardsBoughtInGame: 0,
        wardsKilled: 0,
        wardsPlaced: 0,
        win: true,
      },
      {
        assists: 22,
        baronKills: 0,
        bountyLevel: 0,
        challenges: {
          "12AssistStreakCount": 1,
          abilityUses: 126,
          acesBefore15Minutes: 4,
          alliedJungleMonsterKills: 0,
          baronTakedowns: 0,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 0,
          buffsStolen: 0,
          controlWardsPlaced: 0,
          damagePerMinute: 2577.4075350600265,
          damageTakenOnTeamPercentage: 0.1590726587997555,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 7,
          doubleAces: 0,
          dragonTakedowns: 0,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 1506.7806396484375,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 17,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          flawlessAces: 3,
          fullTeamTakedown: 6,
          gameLength: 879.2444117,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 662.2837844148108,
          hadAfkTeammate: 0,
          hadOpenNexus: 0,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerKillsEarlyJungle: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kda: 3.857142857142857,
          killParticipation: 0.7714285714285715,
          killsNearEnemyTurret: 0,
          killsOnLanersEarlyJungleAsJungler: 0,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 2,
          killsWithHelpFromEpicMonster: 0,
          laneMinionsFirst10Minutes: 22,
          laningPhaseGoldExpAdvantage: -0.051196396350860596,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 4,
          maxKillDeficit: 6,
          maxLevelLeadLaneOpponent: 2,
          moreEnemyJungleThanOpponent: -24,
          mostWardsDestroyedOneSweeper: 0,
          multiKillOneSpell: 0,
          multikills: 0,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 6655,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 2,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          poroExplosions: 0,
          riftHeraldTakedowns: 0,
          scuttleCrabKills: 0,
          shortestTimeToAceFromFirstTakedown: 17.417949600000043,
          skillshotsDodged: 142,
          skillshotsHit: 54,
          snowballsHit: 8,
          soloBaronKills: 0,
          soloKills: 0,
          stealthWardsPlaced: 0,
          survivedSingleDigitHpCount: 0,
          takedownOnFirstTurret: 1,
          takedowns: 27,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirst25Minutes: 27,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 0,
          teamDamagePercentage: 0.20088438664927677,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 0,
          turretPlatesTaken: 0,
          turretTakedowns: 3,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 0,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 0,
          visionScorePerMinute: 0,
          wardTakedowns: 0,
          wardTakedownsBefore20M: 0,
          wardsGuarded: 0,
        },
        champExperience: 12776,
        champLevel: 14,
        championId: 25,
        championName: "Morgana",
        championTransform: 0,
        consumablesPurchased: 0,
        damageDealtToBuildings: 1232,
        damageDealtToObjectives: 1232,
        damageDealtToTurrets: 1232,
        damageSelfMitigated: 6804,
        deaths: 7,
        detectorWardsPlaced: 0,
        doubleKills: 0,
        dragonKills: 0,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        goldEarned: 9705,
        goldSpent: 8435,
        individualPosition: "Invalid",
        inhibitorKills: 0,
        inhibitorTakedowns: 1,
        inhibitorsLost: 0,
        item0: 3157,
        item1: 3020,
        item2: 6655,
        item3: 1052,
        item4: 3112,
        item5: 0,
        item6: 0,
        itemsPurchased: 14,
        killingSprees: 1,
        kills: 5,
        lane: "NONE",
        largestCriticalStrike: 0,
        largestKillingSpree: 3,
        largestMultiKill: 1,
        longestTimeSpentLiving: 221,
        magicDamageDealt: 33096,
        magicDamageDealtToChampions: 14119,
        magicDamageTaken: 7640,
        neutralMinionsKilled: 0,
        nexusKills: 1,
        nexusLost: 0,
        nexusTakedowns: 1,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        participantId: 2,
        pentaKills: 0,
        perks: {
          statPerks: { defense: 5002, flex: 5008, offense: 5008 },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                { perk: 8128, var1: 928, var2: 17, var3: 0 },
                { perk: 8126, var1: 539, var2: 0, var3: 0 },
                { perk: 8138, var1: 30, var2: 0, var3: 0 },
                { perk: 8106, var1: 5, var2: 0, var3: 0 },
              ],
              style: 8100,
            },
            {
              description: "subStyle",
              selections: [
                { perk: 8009, var1: 2464, var2: 0, var3: 0 },
                { perk: 8014, var1: 384, var2: 0, var3: 0 },
              ],
              style: 8000,
            },
          ],
        },
        physicalDamageDealt: 3453,
        physicalDamageDealtToChampions: 470,
        physicalDamageTaken: 7347,
        profileIcon: 5227,
        puuid:
          "K1lgq4Ykend81kgwKN0EBlSWDnNAzGWCka52n9k4cYHe4rpYjWVK-cLD1Q3sxr-zug5g1yVrjGXmaA",
        quadraKills: 0,
        riotIdName: "",
        riotIdTagline: "",
        role: "SUPPORT",
        sightWardsBoughtInGame: 0,
        spell1Casts: 50,
        spell2Casts: 47,
        spell3Casts: 23,
        spell4Casts: 6,
        summoner1Casts: 3,
        summoner1Id: 4,
        summoner2Casts: 19,
        summoner2Id: 32,
        summonerId: "IxZSlFa6zCUQ07RLjy96-4HH5DmHfuuaKgMEefLkjdzCmek",
        summonerLevel: 287,
        summonerName: "YouBetterInt",
        teamEarlySurrendered: false,
        teamId: 100,
        teamPosition: "",
        timeCCingOthers: 33,
        timePlayed: 879,
        totalDamageDealt: 37769,
        totalDamageDealtToChampions: 15660,
        totalDamageShieldedOnTeammates: 1506,
        totalDamageTaken: 15809,
        totalHeal: 2774,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 25,
        totalTimeCCDealt: 99,
        totalTimeSpentDead: 137,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 1220,
        trueDamageDealtToChampions: 1070,
        trueDamageTaken: 821,
        turretKills: 0,
        turretTakedowns: 3,
        turretsLost: 1,
        unrealKills: 0,
        visionScore: 0,
        visionWardsBoughtInGame: 0,
        wardsKilled: 0,
        wardsPlaced: 0,
        win: true,
      },
      {
        assists: 17,
        baronKills: 0,
        bountyLevel: 0,
        challenges: {
          "12AssistStreakCount": 0,
          abilityUses: 96,
          acesBefore15Minutes: 4,
          alliedJungleMonsterKills: 0,
          baronTakedowns: 0,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 150,
          buffsStolen: 0,
          controlWardsPlaced: 0,
          damagePerMinute: 2237.1920339496655,
          damageTakenOnTeamPercentage: 0.24195906080074436,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 8,
          doubleAces: 0,
          dragonTakedowns: 0,
          earlyLaningPhaseGoldExpAdvantage: -0.15729230642318726,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 30,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          flawlessAces: 3,
          fullTeamTakedown: 6,
          gameLength: 879.2444117,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 656.4609580972672,
          hadAfkTeammate: 0,
          hadOpenNexus: 0,
          highestCrowdControlScore: 1,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerKillsEarlyJungle: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kda: 2.625,
          killParticipation: 0.6,
          killsNearEnemyTurret: 0,
          killsOnLanersEarlyJungleAsJungler: 0,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 2,
          killsWithHelpFromEpicMonster: 0,
          laneMinionsFirst10Minutes: 11,
          laningPhaseGoldExpAdvantage: -0.05930262804031372,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 0,
          maxKillDeficit: 6,
          maxLevelLeadLaneOpponent: 2,
          moreEnemyJungleThanOpponent: -24,
          mostWardsDestroyedOneSweeper: 0,
          multiKillOneSpell: 0,
          multikills: 1,
          multikillsAfterAggressiveFlash: 0,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 0,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          poroExplosions: 0,
          riftHeraldTakedowns: 0,
          scuttleCrabKills: 0,
          shortestTimeToAceFromFirstTakedown: 17.417949600000043,
          skillshotsDodged: 160,
          skillshotsHit: 118,
          snowballsHit: 9,
          soloBaronKills: 0,
          soloKills: 0,
          stealthWardsPlaced: 0,
          survivedSingleDigitHpCount: 0,
          takedownOnFirstTurret: 1,
          takedowns: 21,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirst25Minutes: 21,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 0,
          teamDamagePercentage: 0.18868149917649213,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 0,
          teleportTakedowns: 3,
          turretPlatesTaken: 0,
          turretTakedowns: 4,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 0,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 0,
          visionScorePerMinute: 0,
          wardTakedowns: 0,
          wardTakedownsBefore20M: 0,
          wardsGuarded: 0,
        },
        champExperience: 14694,
        champLevel: 15,
        championId: 113,
        championName: "Sejuani",
        championTransform: 0,
        consumablesPurchased: 0,
        damageDealtToBuildings: 977,
        damageDealtToObjectives: 977,
        damageDealtToTurrets: 977,
        damageSelfMitigated: 27979,
        deaths: 8,
        detectorWardsPlaced: 0,
        doubleKills: 1,
        dragonKills: 0,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        goldEarned: 9619,
        goldSpent: 7800,
        individualPosition: "Invalid",
        inhibitorKills: 1,
        inhibitorTakedowns: 1,
        inhibitorsLost: 0,
        item0: 3121,
        item1: 3111,
        item2: 6664,
        item3: 3067,
        item4: 3801,
        item5: 0,
        item6: 2052,
        itemsPurchased: 16,
        killingSprees: 1,
        kills: 4,
        lane: "NONE",
        largestCriticalStrike: 0,
        largestKillingSpree: 2,
        largestMultiKill: 2,
        longestTimeSpentLiving: 147,
        magicDamageDealt: 16044,
        magicDamageDealtToChampions: 7427,
        magicDamageTaken: 10719,
        neutralMinionsKilled: 0,
        nexusKills: 0,
        nexusLost: 0,
        nexusTakedowns: 1,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        participantId: 3,
        pentaKills: 0,
        perks: {
          statPerks: { defense: 5002, flex: 5008, offense: 5005 },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                { perk: 8351, var1: 62, var2: 778, var3: 0 },
                { perk: 8304, var1: 6, var2: 0, var3: 0 },
                { perk: 8345, var1: 3, var2: 0, var3: 0 },
                { perk: 8347, var1: 0, var2: 0, var3: 0 },
              ],
              style: 8300,
            },
            {
              description: "subStyle",
              selections: [
                { perk: 8429, var1: 45, var2: 17, var3: 17 },
                { perk: 8451, var1: 248, var2: 0, var3: 0 },
              ],
              style: 8400,
            },
          ],
        },
        physicalDamageDealt: 15524,
        physicalDamageDealtToChampions: 6536,
        physicalDamageTaken: 11612,
        profileIcon: 1107,
        puuid:
          "LP0h7tup-4EjCm0tvOUb1q2UaCpyxuexEzovYriTwQv61eYelTFatKW9yVrwuC4P-Gawqy2KoZN0Tw",
        quadraKills: 0,
        riotIdName: "",
        riotIdTagline: "",
        role: "SUPPORT",
        sightWardsBoughtInGame: 0,
        spell1Casts: 39,
        spell2Casts: 46,
        spell3Casts: 4,
        spell4Casts: 7,
        summoner1Casts: 5,
        summoner1Id: 4,
        summoner2Casts: 25,
        summoner2Id: 32,
        summonerId: "kGHz9WvtcdzAXQ--7-zRP3fFGEMeOg-UU1K_AngFBzu8_PY",
        summonerLevel: 260,
        summonerName: "Cloner152",
        teamEarlySurrendered: false,
        teamId: 100,
        teamPosition: "",
        timeCCingOthers: 31,
        timePlayed: 879,
        totalDamageDealt: 32783,
        totalDamageDealtToChampions: 14709,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 24047,
        totalHeal: 1730,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 20,
        totalTimeCCDealt: 234,
        totalTimeSpentDead: 129,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 1215,
        trueDamageDealtToChampions: 745,
        trueDamageTaken: 1714,
        turretKills: 1,
        turretTakedowns: 4,
        turretsLost: 1,
        unrealKills: 0,
        visionScore: 0,
        visionWardsBoughtInGame: 0,
        wardsKilled: 0,
        wardsPlaced: 0,
        win: true,
      },
      {
        assists: 11,
        baronKills: 0,
        bountyLevel: 11,
        challenges: {
          "12AssistStreakCount": 0,
          abilityUses: 212,
          acesBefore15Minutes: 4,
          alliedJungleMonsterKills: 0,
          baronTakedowns: 0,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 600,
          buffsStolen: 0,
          controlWardsPlaced: 0,
          damagePerMinute: 5799.810106430274,
          damageTakenOnTeamPercentage: 0.20729775267545408,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 6,
          doubleAces: 0,
          dragonTakedowns: 0,
          earlyLaningPhaseGoldExpAdvantage: -0.0683550238609314,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 0,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          fastestLegendary: 852.5895442,
          flawlessAces: 3,
          fullTeamTakedown: 6,
          gameLength: 879.2444117,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 992.1357395958528,
          hadAfkTeammate: 0,
          hadOpenNexus: 0,
          highestChampionDamage: 1,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerKillsEarlyJungle: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kda: 5.333333333333333,
          killParticipation: 0.9142857142857143,
          killsNearEnemyTurret: 9,
          killsOnLanersEarlyJungleAsJungler: 0,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 6,
          killsWithHelpFromEpicMonster: 0,
          laneMinionsFirst10Minutes: 41,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 1,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 6,
          maxKillDeficit: 6,
          maxLevelLeadLaneOpponent: 2,
          moreEnemyJungleThanOpponent: -24,
          mostWardsDestroyedOneSweeper: 0,
          multiKillOneSpell: 0,
          multikills: 8,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 6673,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 4,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          poroExplosions: 0,
          riftHeraldTakedowns: 0,
          scuttleCrabKills: 0,
          shortestTimeToAceFromFirstTakedown: 17.417949600000043,
          skillshotsDodged: 159,
          skillshotsHit: 93,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 0,
          stealthWardsPlaced: 0,
          survivedSingleDigitHpCount: 0,
          takedownOnFirstTurret: 0,
          takedowns: 32,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirst25Minutes: 32,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 2,
          teamBaronKills: 0,
          teamDamagePercentage: 0.31021860606748713,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 0,
          teleportTakedowns: 2,
          turretPlatesTaken: 0,
          turretTakedowns: 4,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 0,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 0,
          visionScorePerMinute: 0,
          wardTakedowns: 0,
          wardTakedownsBefore20M: 0,
          wardsGuarded: 0,
        },
        champExperience: 15159,
        champLevel: 16,
        championId: 166,
        championName: "Akshan",
        championTransform: 0,
        consumablesPurchased: 0,
        damageDealtToBuildings: 3436,
        damageDealtToObjectives: 3436,
        damageDealtToTurrets: 3436,
        damageSelfMitigated: 16477,
        deaths: 6,
        detectorWardsPlaced: 0,
        doubleKills: 4,
        dragonKills: 0,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        goldEarned: 14538,
        goldSpent: 10600,
        individualPosition: "Invalid",
        inhibitorKills: 0,
        inhibitorTakedowns: 1,
        inhibitorsLost: 0,
        item0: 3006,
        item1: 6673,
        item2: 3091,
        item3: 1038,
        item4: 1018,
        item5: 3184,
        item6: 0,
        itemsPurchased: 16,
        killingSprees: 4,
        kills: 21,
        lane: "NONE",
        largestCriticalStrike: 470,
        largestKillingSpree: 11,
        largestMultiKill: 5,
        longestTimeSpentLiving: 132,
        magicDamageDealt: 11465,
        magicDamageDealtToChampions: 4411,
        magicDamageTaken: 11415,
        neutralMinionsKilled: 0,
        nexusKills: 0,
        nexusLost: 0,
        nexusTakedowns: 1,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        participantId: 4,
        pentaKills: 1,
        perks: {
          statPerks: { defense: 5002, flex: 5008, offense: 5005 },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                { perk: 8005, var1: 1826, var2: 1205, var3: 620 },
                { perk: 8009, var1: 2945, var2: 0, var3: 0 },
                { perk: 9103, var1: 9, var2: 0, var3: 0 },
                { perk: 8014, var1: 952, var2: 0, var3: 0 },
              ],
              style: 8000,
            },
            {
              description: "subStyle",
              selections: [
                { perk: 8401, var1: 625, var2: 0, var3: 0 },
                { perk: 8429, var1: 45, var2: 13, var3: 13 },
              ],
              style: 8400,
            },
          ],
        },
        physicalDamageDealt: 73247,
        physicalDamageDealtToChampions: 19772,
        physicalDamageTaken: 7940,
        profileIcon: 3873,
        puuid:
          "vplw3YSacqeCjFv_ylDMVfefdmbmfbCuZbGHjR4kZizwFZ2EDwmqihvLg1Ws9MiF57cyQgqoFVnGcQ",
        quadraKills: 1,
        riotIdName: "",
        riotIdTagline: "",
        role: "DUO",
        sightWardsBoughtInGame: 0,
        spell1Casts: 75,
        spell2Casts: 11,
        spell3Casts: 114,
        spell4Casts: 12,
        summoner1Casts: 6,
        summoner1Id: 21,
        summoner2Casts: 3,
        summoner2Id: 4,
        summonerId: "hBRvs4sVrlLp3TAMgle62k7-QfPgvXr9u4zZN4HSeJJ9LG4",
        summonerLevel: 380,
        summonerName: "LucarioLG",
        teamEarlySurrendered: false,
        teamId: 100,
        teamPosition: "",
        timeCCingOthers: 0,
        timePlayed: 879,
        totalDamageDealt: 84990,
        totalDamageDealtToChampions: 24183,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 20602,
        totalHeal: 218,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 77,
        totalTimeCCDealt: 57,
        totalTimeSpentDead: 126,
        totalUnitsHealed: 1,
        tripleKills: 2,
        trueDamageDealt: 277,
        trueDamageDealtToChampions: 0,
        trueDamageTaken: 1246,
        turretKills: 2,
        turretTakedowns: 4,
        turretsLost: 1,
        unrealKills: 0,
        visionScore: 0,
        visionWardsBoughtInGame: 0,
        wardsKilled: 0,
        wardsPlaced: 0,
        win: true,
      },
      {
        assists: 21,
        baronKills: 0,
        bountyLevel: 1,
        challenges: {
          "12AssistStreakCount": 0,
          abilityUses: 133,
          acesBefore15Minutes: 4,
          alliedJungleMonsterKills: 0,
          baronTakedowns: 0,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 600,
          buffsStolen: 0,
          controlWardsPlaced: 0,
          damagePerMinute: 3145.2933060478617,
          damageTakenOnTeamPercentage: 0.2525023144972657,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 9,
          doubleAces: 0,
          dragonTakedowns: 0,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 34,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          flawlessAces: 3,
          fullTeamTakedown: 6,
          gameLength: 879.2444117,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 755.0924760045876,
          hadAfkTeammate: 0,
          hadOpenNexus: 0,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerKillsEarlyJungle: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kda: 3.3333333333333335,
          killParticipation: 0.8571428571428571,
          killsNearEnemyTurret: 1,
          killsOnLanersEarlyJungleAsJungler: 0,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 3,
          killsWithHelpFromEpicMonster: 0,
          laneMinionsFirst10Minutes: 24,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 12,
          maxKillDeficit: 6,
          maxLevelLeadLaneOpponent: 2,
          moreEnemyJungleThanOpponent: -24,
          mostWardsDestroyedOneSweeper: 0,
          multiKillOneSpell: 0,
          multikills: 1,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 4644,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 3,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          poroExplosions: 0,
          riftHeraldTakedowns: 0,
          scuttleCrabKills: 0,
          shortestTimeToAceFromFirstTakedown: 17.417949600000043,
          skillshotsDodged: 150,
          skillshotsHit: 103,
          snowballsHit: 3,
          soloBaronKills: 0,
          soloKills: 0,
          stealthWardsPlaced: 0,
          survivedSingleDigitHpCount: 0,
          takedownOnFirstTurret: 0,
          takedowns: 30,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirst25Minutes: 30,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 0,
          teamDamagePercentage: 0.21252412810719384,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 0,
          teleportTakedowns: 2,
          turretPlatesTaken: 0,
          turretTakedowns: 2,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 0,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 0,
          visionScorePerMinute: 0,
          wardTakedowns: 0,
          wardTakedownsBefore20M: 0,
          wardsGuarded: 0,
        },
        champExperience: 12959,
        champLevel: 14,
        championId: 50,
        championName: "Swain",
        championTransform: 0,
        consumablesPurchased: 0,
        damageDealtToBuildings: 1828,
        damageDealtToObjectives: 1828,
        damageDealtToTurrets: 1828,
        damageSelfMitigated: 11209,
        deaths: 9,
        detectorWardsPlaced: 0,
        doubleKills: 1,
        dragonKills: 0,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        goldEarned: 11065,
        goldSpent: 9100,
        individualPosition: "Invalid",
        inhibitorKills: 0,
        inhibitorTakedowns: 1,
        inhibitorsLost: 0,
        item0: 3040,
        item1: 3157,
        item2: 3111,
        item3: 4644,
        item4: 0,
        item5: 0,
        item6: 2052,
        itemsPurchased: 13,
        killingSprees: 2,
        kills: 9,
        lane: "NONE",
        largestCriticalStrike: 0,
        largestKillingSpree: 2,
        largestMultiKill: 2,
        longestTimeSpentLiving: 111,
        magicDamageDealt: 42839,
        magicDamageDealtToChampions: 15401,
        magicDamageTaken: 13805,
        neutralMinionsKilled: 0,
        nexusKills: 0,
        nexusLost: 0,
        nexusTakedowns: 1,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        participantId: 5,
        pentaKills: 0,
        perks: {
          statPerks: { defense: 5003, flex: 5008, offense: 5008 },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                { perk: 8128, var1: 1264, var2: 23, var3: 0 },
                { perk: 8126, var1: 508, var2: 0, var3: 0 },
                { perk: 8138, var1: 30, var2: 0, var3: 0 },
                { perk: 8106, var1: 5, var2: 0, var3: 0 },
              ],
              style: 8100,
            },
            {
              description: "subStyle",
              selections: [
                { perk: 8226, var1: 250, var2: 260, var3: 0 },
                { perk: 8236, var1: 24, var2: 0, var3: 0 },
              ],
              style: 8200,
            },
          ],
        },
        physicalDamageDealt: 2565,
        physicalDamageDealtToChampions: 570,
        physicalDamageTaken: 10275,
        profileIcon: 539,
        puuid:
          "z0GHTgpcCucbXZoOdi0xjdiObG5ntKi5X4E9QKUFjMbZusb2X6FJrgE_J6utv1qwUGnNGaKkRT4rwg",
        quadraKills: 0,
        riotIdName: "",
        riotIdTagline: "",
        role: "SUPPORT",
        sightWardsBoughtInGame: 0,
        spell1Casts: 60,
        spell2Casts: 28,
        spell3Casts: 34,
        spell4Casts: 11,
        summoner1Casts: 12,
        summoner1Id: 32,
        summoner2Casts: 3,
        summoner2Id: 4,
        summonerId: "x5q0ChGoOP4IqtsDbAu7r-k5YpZwmzxqGgLSksxib4g1QrU",
        summonerLevel: 276,
        summonerName: "n64ever",
        teamEarlySurrendered: false,
        teamId: 100,
        teamPosition: "",
        timeCCingOthers: 30,
        timePlayed: 879,
        totalDamageDealt: 46091,
        totalDamageDealtToChampions: 16567,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 25095,
        totalHeal: 6103,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 36,
        totalTimeCCDealt: 198,
        totalTimeSpentDead: 188,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 686,
        trueDamageDealtToChampions: 596,
        trueDamageTaken: 1013,
        turretKills: 1,
        turretTakedowns: 2,
        turretsLost: 1,
        unrealKills: 0,
        visionScore: 0,
        visionWardsBoughtInGame: 0,
        wardsKilled: 0,
        wardsPlaced: 0,
        win: true,
      },
      {
        assists: 14,
        baronKills: 0,
        bountyLevel: 0,
        challenges: {
          "12AssistStreakCount": 0,
          abilityUses: 157,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 0,
          baronTakedowns: 0,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 600,
          buffsStolen: 0,
          controlWardsPlaced: 0,
          damagePerMinute: 3916.0876740378153,
          damageTakenOnTeamPercentage: 0.16047976386750254,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 7,
          doubleAces: 0,
          dragonTakedowns: 0,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 1,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          firstTurretKilledTime: 478.505248,
          flawlessAces: 0,
          fullTeamTakedown: 4,
          gameLength: 879.2444117,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 847.9408856460634,
          hadAfkTeammate: 0,
          hadOpenNexus: 0,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerKillsEarlyJungle: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kda: 3.5714285714285716,
          killParticipation: 0.6097560975609756,
          killsNearEnemyTurret: 5,
          killsOnLanersEarlyJungleAsJungler: 0,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 2,
          killsWithHelpFromEpicMonster: 0,
          laneMinionsFirst10Minutes: 51,
          laningPhaseGoldExpAdvantage: -0.07194000482559204,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 14,
          maxKillDeficit: 0,
          maxLevelLeadLaneOpponent: 1,
          moreEnemyJungleThanOpponent: -24,
          mostWardsDestroyedOneSweeper: 0,
          multiKillOneSpell: 0,
          multikills: 2,
          multikillsAfterAggressiveFlash: 0,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 1,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          poroExplosions: 0,
          riftHeraldTakedowns: 0,
          scuttleCrabKills: 0,
          skillshotsDodged: 124,
          skillshotsHit: 20,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 0,
          stealthWardsPlaced: 0,
          survivedSingleDigitHpCount: 1,
          takedownOnFirstTurret: 0,
          takedowns: 25,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirst25Minutes: 25,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 0,
          teamDamagePercentage: 0.23340359379561143,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 0,
          teleportTakedowns: 1,
          turretPlatesTaken: 0,
          turretTakedowns: 1,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 0,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 0,
          visionScorePerMinute: 0,
          wardTakedowns: 0,
          wardTakedownsBefore20M: 0,
          wardsGuarded: 0,
        },
        champExperience: 12436,
        champLevel: 14,
        championId: 42,
        championName: "Corki",
        championTransform: 0,
        consumablesPurchased: 1,
        damageDealtToBuildings: 1401,
        damageDealtToObjectives: 1401,
        damageDealtToTurrets: 1401,
        damageSelfMitigated: 6082,
        deaths: 7,
        detectorWardsPlaced: 0,
        doubleKills: 2,
        dragonKills: 0,
        firstBloodAssist: false,
        firstBloodKill: false,
        firstTowerAssist: true,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        goldEarned: 12425,
        goldSpent: 11785,
        individualPosition: "Invalid",
        inhibitorKills: 0,
        inhibitorTakedowns: 0,
        inhibitorsLost: 1,
        item0: 3177,
        item1: 6655,
        item2: 3042,
        item3: 3074,
        item4: 1052,
        item5: 3020,
        item6: 2052,
        itemsPurchased: 15,
        killingSprees: 4,
        kills: 11,
        lane: "NONE",
        largestCriticalStrike: 0,
        largestKillingSpree: 3,
        largestMultiKill: 2,
        longestTimeSpentLiving: 220,
        magicDamageDealt: 47700,
        magicDamageDealtToChampions: 17478,
        magicDamageTaken: 7397,
        neutralMinionsKilled: 0,
        nexusKills: 0,
        nexusLost: 1,
        nexusTakedowns: 0,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        participantId: 6,
        pentaKills: 0,
        perks: {
          statPerks: { defense: 5003, flex: 5008, offense: 5005 },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                { perk: 8369, var1: 680, var2: 478, var3: 0 },
                { perk: 8304, var1: 5, var2: 0, var3: 0 },
                { perk: 8345, var1: 3, var2: 0, var3: 0 },
                { perk: 8352, var1: 124, var2: 679, var3: 28 },
              ],
              style: 8300,
            },
            {
              description: "subStyle",
              selections: [
                { perk: 8009, var1: 3373, var2: 0, var3: 0 },
                { perk: 8014, var1: 648, var2: 0, var3: 0 },
              ],
              style: 8000,
            },
          ],
        },
        physicalDamageDealt: 9150,
        physicalDamageDealtToChampions: 2768,
        physicalDamageTaken: 5879,
        profileIcon: 29,
        puuid:
          "ZyAlloitlXWMMqarC45cVU04Wy20jt8ivQAbUXipYeH4QJaG8bbKEe2ce3KScwroiyoscLT1s0OMmw",
        quadraKills: 0,
        riotIdName: "",
        riotIdTagline: "",
        role: "DUO",
        sightWardsBoughtInGame: 0,
        spell1Casts: 42,
        spell2Casts: 17,
        spell3Casts: 28,
        spell4Casts: 70,
        summoner1Casts: 3,
        summoner1Id: 4,
        summoner2Casts: 2,
        summoner2Id: 3,
        summonerId: "e6vzBTEBstxYO1a92aFzKvyrzTkKg-NivVRm8q_msql2OIA",
        summonerLevel: 379,
        summonerName: "Treizeeee",
        teamEarlySurrendered: false,
        teamId: 200,
        teamPosition: "",
        timeCCingOthers: 1,
        timePlayed: 879,
        totalDamageDealt: 57386,
        totalDamageDealtToChampions: 20783,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 13494,
        totalHeal: 1414,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 74,
        totalTimeCCDealt: 155,
        totalTimeSpentDead: 150,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 535,
        trueDamageDealtToChampions: 535,
        trueDamageTaken: 217,
        turretKills: 0,
        turretTakedowns: 1,
        turretsLost: 4,
        unrealKills: 0,
        visionScore: 0,
        visionWardsBoughtInGame: 0,
        wardsKilled: 0,
        wardsPlaced: 0,
        win: false,
      },
      {
        assists: 21,
        baronKills: 0,
        bountyLevel: 0,
        challenges: {
          "12AssistStreakCount": 0,
          abilityUses: 193,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 0,
          baronTakedowns: 0,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 150,
          buffsStolen: 0,
          controlWardsPlaced: 0,
          damagePerMinute: 2899.7021979309557,
          damageTakenOnTeamPercentage: 0.19198047533831097,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 8,
          doubleAces: 0,
          dragonTakedowns: 0,
          earlyLaningPhaseGoldExpAdvantage: -0.007486224174499512,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 19,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          firstTurretKilledTime: 478.505248,
          flawlessAces: 0,
          fullTeamTakedown: 4,
          gameLength: 879.2444117,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 663.0702151666572,
          hadAfkTeammate: 0,
          hadOpenNexus: 0,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerKillsEarlyJungle: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kda: 3.25,
          killParticipation: 0.6341463414634146,
          killsNearEnemyTurret: 2,
          killsOnLanersEarlyJungleAsJungler: 0,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 1,
          killsUnderOwnTurret: 1,
          killsWithHelpFromEpicMonster: 0,
          laneMinionsFirst10Minutes: 19,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 18,
          maxKillDeficit: 0,
          maxLevelLeadLaneOpponent: 1,
          moreEnemyJungleThanOpponent: -24,
          mostWardsDestroyedOneSweeper: 0,
          multiKillOneSpell: 0,
          multikills: 0,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 6656,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 0,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          poroExplosions: 0,
          riftHeraldTakedowns: 0,
          scuttleCrabKills: 0,
          skillshotsDodged: 102,
          skillshotsHit: 37,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 0,
          stealthWardsPlaced: 0,
          survivedSingleDigitHpCount: 0,
          takedownOnFirstTurret: 0,
          takedowns: 26,
          takedownsAfterGainingLevelAdvantage: 1,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirst25Minutes: 26,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 0,
          teamDamagePercentage: 0.17259500672731873,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 0,
          teleportTakedowns: 1,
          turretPlatesTaken: 0,
          turretTakedowns: 1,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 0,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 0,
          visionScorePerMinute: 0,
          wardTakedowns: 0,
          wardTakedownsBefore20M: 0,
          wardsGuarded: 0,
        },
        champExperience: 11944,
        champLevel: 14,
        championId: 4,
        championName: "TwistedFate",
        championTransform: 0,
        consumablesPurchased: 2,
        damageDealtToBuildings: 911,
        damageDealtToObjectives: 911,
        damageDealtToTurrets: 911,
        damageSelfMitigated: 6196,
        deaths: 8,
        detectorWardsPlaced: 0,
        doubleKills: 0,
        dragonKills: 0,
        firstBloodAssist: true,
        firstBloodKill: false,
        firstTowerAssist: true,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        goldEarned: 9716,
        goldSpent: 8950,
        individualPosition: "Invalid",
        inhibitorKills: 0,
        inhibitorTakedowns: 0,
        inhibitorsLost: 1,
        item0: 6656,
        item1: 3094,
        item2: 3020,
        item3: 3113,
        item4: 3057,
        item5: 3108,
        item6: 2052,
        itemsPurchased: 14,
        killingSprees: 0,
        kills: 5,
        lane: "NONE",
        largestCriticalStrike: 147,
        largestKillingSpree: 0,
        largestMultiKill: 1,
        longestTimeSpentLiving: 174,
        magicDamageDealt: 37761,
        magicDamageDealtToChampions: 13589,
        magicDamageTaken: 9940,
        neutralMinionsKilled: 0,
        nexusKills: 0,
        nexusLost: 1,
        nexusTakedowns: 0,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        participantId: 7,
        pentaKills: 0,
        perks: {
          statPerks: { defense: 5003, flex: 5008, offense: 5008 },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                { perk: 8128, var1: 964, var2: 19, var3: 0 },
                { perk: 8126, var1: 484, var2: 0, var3: 0 },
                { perk: 8138, var1: 30, var2: 0, var3: 0 },
                { perk: 8135, var1: 1258, var2: 5, var3: 0 },
              ],
              style: 8100,
            },
            {
              description: "subStyle",
              selections: [
                { perk: 8226, var1: 250, var2: 593, var3: 0 },
                { perk: 8237, var1: 386, var2: 0, var3: 0 },
              ],
              style: 8200,
            },
          ],
        },
        physicalDamageDealt: 4256,
        physicalDamageDealtToChampions: 1304,
        physicalDamageTaken: 5581,
        profileIcon: 4061,
        puuid:
          "LHCBtlfzXPjV9LDyRsC8fQaJppitSwx5RFls-xzTHwKDgYauUutQwL5m5y3fwD2RERBcMBgiGPTaFQ",
        quadraKills: 0,
        riotIdName: "",
        riotIdTagline: "",
        role: "SUPPORT",
        sightWardsBoughtInGame: 0,
        spell1Casts: 73,
        spell2Casts: 114,
        spell3Casts: 0,
        spell4Casts: 6,
        summoner1Casts: 3,
        summoner1Id: 4,
        summoner2Casts: 3,
        summoner2Id: 3,
        summonerId: "eGNxkaAHmJ9-IgvZhM_uGxy9PNok6FARMVwPkbkkQ-2Y41x3",
        summonerLevel: 371,
        summonerName: "MKørs",
        teamEarlySurrendered: false,
        teamId: 200,
        teamPosition: "",
        timeCCingOthers: 20,
        timePlayed: 879,
        totalDamageDealt: 42492,
        totalDamageDealtToChampions: 15368,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 16143,
        totalHeal: 469,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 24,
        totalTimeCCDealt: 52,
        totalTimeSpentDead: 174,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 473,
        trueDamageDealtToChampions: 473,
        trueDamageTaken: 621,
        turretKills: 0,
        turretTakedowns: 1,
        turretsLost: 4,
        unrealKills: 0,
        visionScore: 0,
        visionWardsBoughtInGame: 0,
        wardsKilled: 0,
        wardsPlaced: 0,
        win: false,
      },
      {
        assists: 18,
        baronKills: 0,
        bountyLevel: 0,
        challenges: {
          "12AssistStreakCount": 0,
          abilityUses: 146,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 0,
          baronTakedowns: 0,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 0,
          buffsStolen: 0,
          controlWardsPlaced: 0,
          damagePerMinute: 2952.028998377767,
          damageTakenOnTeamPercentage: 0.173301893006608,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 9,
          doubleAces: 0,
          dragonTakedowns: 0,
          earlyLaningPhaseGoldExpAdvantage: -0.04200953245162964,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 4,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          firstTurretKilledTime: 478.505248,
          flawlessAces: 0,
          fullTeamTakedown: 4,
          gameLength: 879.2444117,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 619.1391844233771,
          hadAfkTeammate: 0,
          hadOpenNexus: 0,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerKillsEarlyJungle: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kda: 2.3333333333333335,
          killParticipation: 0.5121951219512195,
          killsNearEnemyTurret: 0,
          killsOnLanersEarlyJungleAsJungler: 0,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 0,
          killsWithHelpFromEpicMonster: 0,
          laneMinionsFirst10Minutes: 18,
          laningPhaseGoldExpAdvantage: -0.013692021369934082,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 29,
          maxKillDeficit: 0,
          maxLevelLeadLaneOpponent: 1,
          moreEnemyJungleThanOpponent: -24,
          mostWardsDestroyedOneSweeper: 0,
          multiKillOneSpell: 0,
          multikills: 0,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 6653,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 1,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          poroExplosions: 0,
          riftHeraldTakedowns: 0,
          scuttleCrabKills: 0,
          skillshotsDodged: 118,
          skillshotsHit: 28,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 1,
          stealthWardsPlaced: 0,
          survivedSingleDigitHpCount: 0,
          takedownOnFirstTurret: 1,
          takedowns: 21,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirst25Minutes: 21,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 0,
          teamDamagePercentage: 0.23545237137203315,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 0,
          teleportTakedowns: 1,
          turretPlatesTaken: 0,
          turretTakedowns: 1,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 0,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 0,
          visionScorePerMinute: 0,
          wardTakedowns: 0,
          wardTakedownsBefore20M: 0,
          wardsGuarded: 0,
        },
        champExperience: 12371,
        champLevel: 14,
        championId: 74,
        championName: "Heimerdinger",
        championTransform: 0,
        consumablesPurchased: 0,
        damageDealtToBuildings: 1247,
        damageDealtToObjectives: 1247,
        damageDealtToTurrets: 1247,
        damageSelfMitigated: 5791,
        deaths: 9,
        detectorWardsPlaced: 0,
        doubleKills: 0,
        dragonKills: 0,
        firstBloodAssist: true,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        goldEarned: 9072,
        goldSpent: 8685,
        individualPosition: "Invalid",
        inhibitorKills: 0,
        inhibitorTakedowns: 0,
        inhibitorsLost: 1,
        item0: 3157,
        item1: 3020,
        item2: 6653,
        item3: 1052,
        item4: 3112,
        item5: 1028,
        item6: 0,
        itemsPurchased: 16,
        killingSprees: 0,
        kills: 3,
        lane: "NONE",
        largestCriticalStrike: 0,
        largestKillingSpree: 0,
        largestMultiKill: 1,
        longestTimeSpentLiving: 165,
        magicDamageDealt: 40263,
        magicDamageDealtToChampions: 19733,
        magicDamageTaken: 9342,
        neutralMinionsKilled: 0,
        nexusKills: 0,
        nexusLost: 1,
        nexusTakedowns: 0,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        participantId: 8,
        pentaKills: 0,
        perks: {
          statPerks: { defense: 5002, flex: 5008, offense: 5008 },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                { perk: 8229, var1: 1666, var2: 0, var3: 0 },
                { perk: 8226, var1: 250, var2: 360, var3: 0 },
                { perk: 8210, var1: 9, var2: 0, var3: 0 },
                { perk: 8236, var1: 24, var2: 0, var3: 0 },
              ],
              style: 8200,
            },
            {
              description: "subStyle",
              selections: [
                { perk: 8138, var1: 30, var2: 0, var3: 0 },
                { perk: 8106, var1: 5, var2: 0, var3: 0 },
              ],
              style: 8100,
            },
          ],
        },
        physicalDamageDealt: 1981,
        physicalDamageDealtToChampions: 218,
        physicalDamageTaken: 5118,
        profileIcon: 4862,
        puuid:
          "0l86qSi2UIk4xuEjGoj7ifBUZqqtlGj07ZRQtEwqi9YM0NUtoEHJe0taiKrkgebdG7JLr9ZO9Q78Pg",
        quadraKills: 0,
        riotIdName: "",
        riotIdTagline: "",
        role: "SUPPORT",
        sightWardsBoughtInGame: 0,
        spell1Casts: 51,
        spell2Casts: 54,
        spell3Casts: 32,
        spell4Casts: 9,
        summoner1Casts: 4,
        summoner1Id: 4,
        summoner2Casts: 6,
        summoner2Id: 14,
        summonerId: "gkH6TMNLPgsyinHFxn0eJkIpwiUo4Tz5OnSTYpZRG4QzAhw",
        summonerLevel: 375,
        summonerName: "KawaiiKakashi",
        teamEarlySurrendered: false,
        teamId: 200,
        teamPosition: "",
        timeCCingOthers: 13,
        timePlayed: 879,
        totalDamageDealt: 43259,
        totalDamageDealtToChampions: 20965,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 14573,
        totalHeal: 931,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 36,
        totalTimeCCDealt: 136,
        totalTimeSpentDead: 192,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 1014,
        trueDamageDealtToChampions: 1014,
        trueDamageTaken: 112,
        turretKills: 1,
        turretTakedowns: 1,
        turretsLost: 4,
        unrealKills: 0,
        visionScore: 0,
        visionWardsBoughtInGame: 0,
        wardsKilled: 0,
        wardsPlaced: 0,
        win: false,
      },
      {
        assists: 15,
        baronKills: 0,
        bountyLevel: 0,
        challenges: {
          "12AssistStreakCount": 0,
          abilityUses: 137,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 0,
          baronTakedowns: 0,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 0,
          buffsStolen: 0,
          controlWardsPlaced: 0,
          damagePerMinute: 2344.3465392798016,
          damageTakenOnTeamPercentage: 0.25436725829549134,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 10,
          doubleAces: 0,
          dragonTakedowns: 0,
          earlyLaningPhaseGoldExpAdvantage: -0.009685754776000977,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 0,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          firstTurretKilledTime: 478.505248,
          flawlessAces: 0,
          fullTeamTakedown: 4,
          gameLength: 879.2444117,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 668.6482023534253,
          hadAfkTeammate: 0,
          hadOpenNexus: 0,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerKillsEarlyJungle: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kda: 2.2,
          killParticipation: 0.5365853658536586,
          killsNearEnemyTurret: 3,
          killsOnLanersEarlyJungleAsJungler: 0,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 2,
          killsWithHelpFromEpicMonster: 0,
          laneMinionsFirst10Minutes: 13,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 13,
          maxKillDeficit: 0,
          maxLevelLeadLaneOpponent: 1,
          moreEnemyJungleThanOpponent: -24,
          mostWardsDestroyedOneSweeper: 0,
          multiKillOneSpell: 0,
          multikills: 0,
          multikillsAfterAggressiveFlash: 0,
          mythicItemUsed: 6692,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 2,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          poroExplosions: 0,
          riftHeraldTakedowns: 0,
          scuttleCrabKills: 0,
          skillshotsDodged: 138,
          skillshotsHit: 52,
          snowballsHit: 0,
          soloBaronKills: 0,
          soloKills: 2,
          stealthWardsPlaced: 0,
          survivedSingleDigitHpCount: 0,
          takedownOnFirstTurret: 0,
          takedowns: 22,
          takedownsAfterGainingLevelAdvantage: 0,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirst25Minutes: 22,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 0,
          teamDamagePercentage: 0.2191092438012524,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 0,
          teleportTakedowns: 3,
          turretPlatesTaken: 0,
          turretTakedowns: 1,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 0,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 0,
          visionScorePerMinute: 0,
          wardTakedowns: 0,
          wardTakedownsBefore20M: 0,
          wardsGuarded: 0,
        },
        champExperience: 12328,
        champLevel: 14,
        championId: 121,
        championName: "Khazix",
        championTransform: 0,
        consumablesPurchased: 2,
        damageDealtToBuildings: 720,
        damageDealtToObjectives: 720,
        damageDealtToTurrets: 720,
        damageSelfMitigated: 23870,
        deaths: 10,
        detectorWardsPlaced: 0,
        doubleKills: 0,
        dragonKills: 0,
        firstBloodAssist: false,
        firstBloodKill: true,
        firstTowerAssist: true,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        goldEarned: 9798,
        goldSpent: 9600,
        individualPosition: "Invalid",
        inhibitorKills: 0,
        inhibitorTakedowns: 0,
        inhibitorsLost: 1,
        item0: 3177,
        item1: 6692,
        item2: 3156,
        item3: 3111,
        item4: 3070,
        item5: 3133,
        item6: 2052,
        itemsPurchased: 29,
        killingSprees: 0,
        kills: 7,
        lane: "NONE",
        largestCriticalStrike: 0,
        largestKillingSpree: 0,
        largestMultiKill: 1,
        longestTimeSpentLiving: 110,
        magicDamageDealt: 548,
        magicDamageDealtToChampions: 548,
        magicDamageTaken: 9949,
        neutralMinionsKilled: 0,
        nexusKills: 0,
        nexusLost: 1,
        nexusTakedowns: 0,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        participantId: 9,
        pentaKills: 0,
        perks: {
          statPerks: { defense: 5001, flex: 5008, offense: 5008 },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                { perk: 8128, var1: 859, var2: 17, var3: 0 },
                { perk: 8139, var1: 1034, var2: 0, var3: 0 },
                { perk: 8138, var1: 18, var2: 0, var3: 0 },
                { perk: 8135, var1: 1100, var2: 5, var3: 0 },
              ],
              style: 8100,
            },
            {
              description: "subStyle",
              selections: [
                { perk: 8226, var1: 250, var2: 279, var3: 0 },
                { perk: 8210, var1: 27, var2: 0, var3: 0 },
              ],
              style: 8200,
            },
          ],
        },
        physicalDamageDealt: 33193,
        physicalDamageDealtToChampions: 18349,
        physicalDamageTaken: 10591,
        profileIcon: 1113,
        puuid:
          "JHlfELT_G1bVM0J7_dH74PbOHF9ym-49nf5aT9eDL0k2jyrKI22PZ4foPCCh-RkxIMAh36q5Apk1-A",
        quadraKills: 0,
        riotIdName: "",
        riotIdTagline: "",
        role: "SUPPORT",
        sightWardsBoughtInGame: 0,
        spell1Casts: 51,
        spell2Casts: 48,
        spell3Casts: 26,
        spell4Casts: 12,
        summoner1Casts: 6,
        summoner1Id: 14,
        summoner2Casts: 4,
        summoner2Id: 4,
        summonerId: "KuAxyuEJ2I33z7Wziq2aEMVMOQmqOvi9-rO1VCQxe5c3-w4",
        summonerLevel: 189,
        summonerName: "Εrik",
        teamEarlySurrendered: false,
        teamId: 200,
        teamPosition: "",
        timeCCingOthers: 11,
        timePlayed: 879,
        totalDamageDealt: 34354,
        totalDamageDealtToChampions: 19510,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 21389,
        totalHeal: 4129,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 20,
        totalTimeCCDealt: 163,
        totalTimeSpentDead: 216,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 612,
        trueDamageDealtToChampions: 612,
        trueDamageTaken: 849,
        turretKills: 0,
        turretTakedowns: 1,
        turretsLost: 4,
        unrealKills: 0,
        visionScore: 0,
        visionWardsBoughtInGame: 0,
        wardsKilled: 0,
        wardsPlaced: 0,
        win: false,
      },
      {
        assists: 12,
        baronKills: 0,
        bountyLevel: 0,
        challenges: {
          "12AssistStreakCount": 0,
          abilityUses: 116,
          acesBefore15Minutes: 0,
          alliedJungleMonsterKills: 0,
          baronTakedowns: 0,
          blastConeOppositeOpponentCount: 0,
          bountyGold: 600,
          buffsStolen: 0,
          controlWardsPlaced: 0,
          damagePerMinute: 1056.7563432999411,
          damageTakenOnTeamPercentage: 0.21987060949208714,
          dancedWithRiftHerald: 0,
          deathsByEnemyChamps: 7,
          doubleAces: 0,
          dragonTakedowns: 0,
          earlyLaningPhaseGoldExpAdvantage: 0,
          effectiveHealAndShielding: 0,
          elderDragonKillsWithOpposingSoul: 0,
          elderDragonMultikills: 0,
          enemyChampionImmobilizations: 33,
          enemyJungleMonsterKills: 0,
          epicMonsterKillsNearEnemyJungler: 0,
          epicMonsterKillsWithin30SecondsOfSpawn: 0,
          epicMonsterSteals: 0,
          firstTurretKilledTime: 478.505248,
          flawlessAces: 0,
          fullTeamTakedown: 4,
          gameLength: 879.2444117,
          getTakedownsInAllLanesEarlyJungleAsLaner: 0,
          goldPerMinute: 811.7130910605821,
          hadAfkTeammate: 0,
          hadOpenNexus: 0,
          initialBuffCount: 0,
          initialCrabCount: 0,
          jungleCsBefore10Minutes: 0,
          junglerKillsEarlyJungle: 0,
          junglerTakedownsNearDamagedEpicMonster: 0,
          kda: 3,
          killParticipation: 0.5121951219512195,
          killsNearEnemyTurret: 3,
          killsOnLanersEarlyJungleAsJungler: 0,
          killsOnOtherLanesEarlyJungleAsLaner: 0,
          killsOnRecentlyHealedByAramPack: 0,
          killsUnderOwnTurret: 3,
          killsWithHelpFromEpicMonster: 0,
          laneMinionsFirst10Minutes: 2,
          laningPhaseGoldExpAdvantage: 0,
          legendaryCount: 0,
          lostAnInhibitor: 0,
          maxCsAdvantageOnLaneOpponent: 0,
          maxKillDeficit: 0,
          maxLevelLeadLaneOpponent: 1,
          moreEnemyJungleThanOpponent: -24,
          mostWardsDestroyedOneSweeper: 0,
          multiKillOneSpell: 0,
          multikills: 2,
          multikillsAfterAggressiveFlash: 0,
          outerTurretExecutesBefore10Minutes: 0,
          outnumberedKills: 2,
          outnumberedNexusKill: 0,
          perfectDragonSoulsTaken: 0,
          perfectGame: 0,
          poroExplosions: 0,
          riftHeraldTakedowns: 0,
          scuttleCrabKills: 0,
          skillshotsDodged: 111,
          skillshotsHit: 46,
          snowballsHit: 6,
          soloBaronKills: 0,
          soloKills: 0,
          stealthWardsPlaced: 0,
          survivedSingleDigitHpCount: 0,
          takedownOnFirstTurret: 0,
          takedowns: 21,
          takedownsAfterGainingLevelAdvantage: 1,
          takedownsBeforeJungleMinionSpawn: 0,
          takedownsFirst25Minutes: 21,
          takedownsInAlcove: 0,
          takedownsInEnemyFountain: 0,
          teamBaronKills: 0,
          teamDamagePercentage: 0.1394397843037843,
          teamElderDragonKills: 0,
          teamRiftHeraldKills: 0,
          turretPlatesTaken: 0,
          turretTakedowns: 0,
          turretsTakenWithRiftHerald: 0,
          twentyMinionsIn3SecondsCount: 0,
          unseenRecalls: 0,
          visionScoreAdvantageLaneOpponent: 0,
          visionScorePerMinute: 0,
          wardTakedowns: 0,
          wardTakedownsBefore20M: 0,
          wardsGuarded: 0,
        },
        champExperience: 12349,
        champLevel: 14,
        championId: 555,
        championName: "Pyke",
        championTransform: 0,
        consumablesPurchased: 0,
        damageDealtToBuildings: 130,
        damageDealtToObjectives: 130,
        damageDealtToTurrets: 130,
        damageSelfMitigated: 15159,
        deaths: 7,
        detectorWardsPlaced: 0,
        doubleKills: 2,
        dragonKills: 0,
        firstBloodAssist: true,
        firstBloodKill: false,
        firstTowerAssist: false,
        firstTowerKill: false,
        gameEndedInEarlySurrender: false,
        gameEndedInSurrender: false,
        goldEarned: 11894,
        goldSpent: 11400,
        individualPosition: "Invalid",
        inhibitorKills: 0,
        inhibitorTakedowns: 0,
        inhibitorsLost: 1,
        item0: 6696,
        item1: 3142,
        item2: 6691,
        item3: 3111,
        item4: 1031,
        item5: 1028,
        item6: 2052,
        itemsPurchased: 16,
        killingSprees: 3,
        kills: 9,
        lane: "NONE",
        largestCriticalStrike: 0,
        largestKillingSpree: 3,
        largestMultiKill: 2,
        longestTimeSpentLiving: 191,
        magicDamageDealt: 0,
        magicDamageDealtToChampions: 0,
        magicDamageTaken: 10581,
        neutralMinionsKilled: 0,
        nexusKills: 0,
        nexusLost: 1,
        nexusTakedowns: 0,
        objectivesStolen: 0,
        objectivesStolenAssists: 0,
        participantId: 10,
        pentaKills: 0,
        perks: {
          statPerks: { defense: 5001, flex: 5008, offense: 5008 },
          styles: [
            {
              description: "primaryStyle",
              selections: [
                { perk: 9923, var1: 20, var2: 51, var3: 0 },
                { perk: 8139, var1: 1143, var2: 0, var3: 0 },
                { perk: 8138, var1: 18, var2: 0, var3: 0 },
                { perk: 8135, var1: 615, var2: 5, var3: 0 },
              ],
              style: 8100,
            },
            {
              description: "subStyle",
              selections: [
                { perk: 8242, var1: 64, var2: 0, var3: 0 },
                { perk: 8444, var1: 884, var2: 0, var3: 0 },
              ],
              style: 8400,
            },
          ],
        },
        physicalDamageDealt: 12999,
        physicalDamageDealtToChampions: 9929,
        physicalDamageTaken: 7297,
        profileIcon: 4421,
        puuid:
          "0cnhrppdsw0JBuYQfvj8x-UoLCj-TwpEn4qS_GcJbY4yTQIGkSdYeZKalxJKWiGMmKTK3DENZHNg1g",
        quadraKills: 0,
        riotIdName: "",
        riotIdTagline: "",
        role: "SUPPORT",
        sightWardsBoughtInGame: 0,
        spell1Casts: 46,
        spell2Casts: 29,
        spell3Casts: 27,
        spell4Casts: 14,
        summoner1Casts: 4,
        summoner1Id: 4,
        summoner2Casts: 12,
        summoner2Id: 32,
        summonerId: "-VRyZRqPvMUAIdUBUVW8V-6wRMSUWc2xhfS1mvvcsyfjOjw",
        summonerLevel: 197,
        summonerName: "Per Vérs",
        teamEarlySurrendered: false,
        teamId: 200,
        teamPosition: "",
        timeCCingOthers: 25,
        timePlayed: 879,
        totalDamageDealt: 15485,
        totalDamageDealtToChampions: 12416,
        totalDamageShieldedOnTeammates: 0,
        totalDamageTaken: 18489,
        totalHeal: 6278,
        totalHealsOnTeammates: 0,
        totalMinionsKilled: 3,
        totalTimeCCDealt: 52,
        totalTimeSpentDead: 142,
        totalUnitsHealed: 1,
        tripleKills: 0,
        trueDamageDealt: 2486,
        trueDamageDealtToChampions: 2486,
        trueDamageTaken: 610,
        turretKills: 0,
        turretTakedowns: 0,
        turretsLost: 4,
        unrealKills: 0,
        visionScore: 0,
        visionWardsBoughtInGame: 0,
        wardsKilled: 0,
        wardsPlaced: 0,
        win: false,
      },
    ],
    platformId: "EUW1",
    queueId: 450,
    teams: [
      {
        bans: [],
        objectives: {
          baron: { first: false, kills: 0 },
          champion: { first: false, kills: 41 },
          dragon: { first: false, kills: 0 },
          inhibitor: { first: true, kills: 1 },
          riftHerald: { first: false, kills: 0 },
          tower: { first: false, kills: 4 },
        },
        teamId: 100,
        win: true,
      },
      {
        bans: [],
        objectives: {
          baron: { first: false, kills: 0 },
          champion: { first: true, kills: 35 },
          dragon: { first: false, kills: 0 },
          inhibitor: { first: false, kills: 0 },
          riftHerald: { first: false, kills: 0 },
          tower: { first: true, kills: 1 },
        },
        teamId: 200,
        win: false,
      },
    ],
    tournamentCode: "",
  },
};

export const USER = {
  username: "Wesleý",
  id: "LX9mkE_WIebje-VX0HS13MNgWkOw42OU2mRmu0vh9mst1WQ",
};
